version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

  web:
    build: ../.
    working_dir: /code/
    command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  celery:
    build: ../.
    working_dir: /code/
    command: celery -A redditcr worker -l debug
    volumes:
      - ../web:/code
    depends_on:
      - web
      - rabbitmq

  celery-beat:
    build: ../.
    working_dir: /code/
    command: celery -A redditcr beat -l debug -S django
    volumes:
      - ../web:/code
    depends_on:
      - web
      - rabbitmq

